name: alertshow
description: Flutter package to show diferents types of alert message.
version: 0.1.4
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter